name: Deploy preview

on:
  pull_request:
    branches:
      - test-gh-preview-deploy
    types: [closed]
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  remove:
    runs-on: ubuntu-20.04
    continue-on-error: true
    if: github.event.pull_request.merged == true
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set Git Config
        run: git config --global user.email "kulkarni.kashyap@freshworks.com" && git config --global user.name "kulkarni.kashyap"

      - name: Remove File
        run: ./delete-docs.sh ${{env.PR_NUMBER}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
