name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'

    # Installs the dependencies
    - name: Install Dependencies
      run: npm ci

    # Runs lints
    - name: Run Linter
      run: npm run code-sanity
    
    # Runs tests
    - name: Runs tests
      run: npm run test
    
    # Builds components
    - name: Builds Components
      run: npm run build:components
    
    # Creates Release and Publishes to NPM
    - name: Semantic Release
      run: npx semantic-release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
