name: Release

on:
  push:
    branches: [ master, next, canary ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Installs Git
    - name: Install Git
      run: brew install git

    - uses: actions/checkout@v2
  
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install npm 7
      run: npx i npm@7

    # Installs the dependencies
    - name: Install Dependencies
      run: npm ci

    # Runs lints
    - name: Run Linter
      run: npm run code-sanity
    
    # Build
    - name: Build
      run: npm run build
    
    # Runs tests
    - name: Runs tests
      run: npm run test


    # Creates git tags
    - name: Create Git Tags
      run: npm run update-version:ci

    # Publish to NPM 
    - name: NPM Publish
      run: npm run release:ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    